apiVersion: v1
kind: Service
metadata:
  name: pulsar-mongo
  namespace: default
spec:
  selector:
    app: pulsar-mongo
  type: ClusterIP
  ports:
    - name: pulsar-mongo
      port: 27017
      targetPort: 27017
