apiVersion: v1
kind: Service
metadata:
  name: pulsar-mongo
  namespace: default
spec:
  selector:
    app: pulsar-mongo
  type: NodePort
  ports:
    - name: pulsar-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 27000