apiVersion: v1
kind: Secret
metadata:
  name: pulsar-mongo-secret
  namespace: default
type: Opaque
data:
  username: MjUy
  password: YWRtaW4=
  # Example:
  # password: {{ .Values.password | b64enc }}