kube.depapiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-mongo
  namespace: default
  labels:
    app: pulsar-mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulsar-mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pulsar-mongo
    spec:
      containers:
        - name: pulsar-mongo
          image: dockerhubusername/IMAGEname:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
              
          # env:
          # - name : FRONTEND_HOST
          #   valueFrom:
          #     configMapKeyRef:
          #       name: pulsar-db-config
          #       key: FRONTEND_HOST
