apiVersion: v1
kind: Service
metadata:
  name: pulsar-frontend
  namespace: default
spec:
  selector:
    app: pulsar-frontend
  type: NodePort
  ports:
    - name: pulsar-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000