apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-frontend
  namespace: default
  labels:
    app: pulsar-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulsar-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pulsar-frontend
    spec:
      containers:
        - name: pulsar-frontend
          image: dockerhubusername/IMAGEname:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
          - name : FRONTEND_HOST
            valueFrom:
              configMapKeyRef:
                name: pulsar-frontend-config
                key: FRONTEND_HOST
