apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-backend
  namespace: default
  labels:
    app: pulsar-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulsar-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pulsar-backend
    spec:
      containers:
        - name: pulsar-backend
          image: dockerhubusername/IMAGEname:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
          - name : MONGO_URL
            valueFrom:
              configMapKeyRef:
                name: pulsar-backend-config
                key: MONGO_URL
