apiVersion: v1
kind: Secret
metadata:
  name: pulsar-backend-secret
  namespace: default
type: Opaque
data:
  MONGO_PASSWORD: MjUy
  MONGO_USERNAME: YWRtaW4=
  # Example:
  # password: {{ .Values.password | b64enc }}