apiVersion: v1
kind: Service
metadata:
  name: pulsar-backend
  namespace: default
spec:
  selector:
    app: pulsar-backend
  type: NodePort
  ports:
    - name: pulsar-backend
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8000